version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    user: node
    command: ["npm", "start"]